//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carbrand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carbrand()
        {
            this.Models = new HashSet<Model>();
        }
    
        public decimal carbrand_id { get; set; }
        public string carbrand_name { get; set; }
        public string carbrand_country_name { get; set; }
        public string carbrand_url { get; set; }
        public Nullable<System.DateTime> carbrand_foundation_year { get; set; }
        public string carbrand_yearly_traffic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Model> Models { get; set; }
    }
}
