//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;

    public partial class CarBrand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarBrand()
        {
            this.Models = new HashSet<Model>();
        }
    
        public decimal Carbrand_Id { get; set; }
        public string Carbrand_Name { get; set; }
        public string Carbrand_Country_Name { get; set; }
        public string Carbrand_Url { get; set; }
        public Nullable<System.DateTime> Carbrand_Foundation_Year { get; set; }
        public string Carbrand_Yearly_Traffic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Model> Models { get; set; }
    }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member