//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarShopDataEntities : DbContext
    {
        public CarShopDataEntities()
            : base("name=CarShopDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carbrand> Carbrands { get; set; }
        public virtual DbSet<Extra> Extras { get; set; }
        public virtual DbSet<ModelExtraswitch> ModelExtraswitches { get; set; }
        public virtual DbSet<Model> Models { get; set; }
    }
}
