//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
namespace CarShop.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarShopDataEntities1 : DbContext
    {
        public CarShopDataEntities1()
            : base("name=CarShopDataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarBrand> CarBrands { get; set; }
        public virtual DbSet<Extra> Extras { get; set; }
        public virtual DbSet<ModelExtraswitch> ModelExtraswitches { get; set; }
        public virtual DbSet<Model> Models { get; set; }
    }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member