//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Model()
        {
            this.ModelExtraswitches = new HashSet<ModelExtraswitch>();
        }
    
        public decimal model_id { get; set; }
        public decimal carbrand_id { get; set; }
        public string model_name { get; set; }
        public Nullable<System.DateTime> model_release_day { get; set; }
        public decimal model_engine_volume { get; set; }
        public decimal model_horsepower { get; set; }
        public decimal model_base_price { get; set; }
    
        public virtual Carbrand Carbrand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelExtraswitch> ModelExtraswitches { get; set; }
    }
}
