//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelExtraswitch
    {
        public decimal modelExtraswitch_id { get; set; }
        public decimal model_id { get; set; }
        public decimal extra_id { get; set; }
    
        public virtual Extra Extra { get; set; }
        public virtual Model Model { get; set; }
    }
}
